[package]
name = "sysy_compiler"
version = "0.1.0"
authors = ["snow276 <leo.cao@stu.pku.edu.cn>"]
edition = "2021"

[build-dependencies]
lalrpop = "0.22.0"

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer"] }
